name: Deploy to EC2

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa

    - name: Copy files to EC2
      run: |
        rsync -avz --delete \
          --exclude '.git' \
          --exclude 'node_modules' \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ ubuntu@${{ secrets.EC2_HOST }}:/opt/finance-app

    - name: Restart backend on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'sudo systemctl restart finance-app'