name: Deploy to EC2

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/authorized_keys
        chmod 600 ~/.ssh/authorized_keys
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Copy files to EC2
      run: |
        rsync -avz --delete \
          --exclude '.git' \
          --exclude 'node_modules' \
          ./ ${{ secrets.EC2_HOST }}:/opt/finance-app

    - name: Restart backend on EC2
      run: |
        ssh ${{ secrets.EC2_HOST }} 'sudo systemctl restart finance-app'
